import Nav from "./Nav";
import Footer from "./Footer";
import { motion, AnimatePresence } from "framer-motion"



const variants = {
    hidden: { opacity: 0, x: 0, y: 0 },
    enter: { opacity: 1, x: 0, y: 0, },
    exit: { opacity: 0, x: 0, y: 0 },
}

const Layout = ({ children }) => {
    return (
        <>
            <Nav />

            <motion.main
                variants={variants} // Pass the variant object into Framer Motion 
                initial="hidden" // Set the initial state to variants.hidden
                animate="enter" // Animated state to variants.enter
                exit="exit" // Exit state (used later) to variants.exit
                transition={{ type: 'linear', duration: 1 }} // Set the transition to linear
            >
                <div className="min-h-screen w-full h-full bg-fixed bg-[url('/assets/background.jpg')] bg-cover overflow-hidden">
                    <div className="w-full h-full absolute  bg-gradient-to-b from-[#08250D]" />

                    {children}

                </div>
            </motion.main>

            <Footer />


        </>

    );
}

export default Layout;


// import Head from "next/head";
// import Layout from "../components/Layout";
// import Link from 'next/link';
// import React, { useState, useEffect } from "react";
// import { useRouter } from "next/router";
// import '@fancyapps/ui/dist/carousel.css';

// const Corner = () => {

//     return (
//         <Layout>
//             <Head>
//                 <title>Corner - Polo Football Park</title>
//                 <meta name="description" content="Generated by create next app" />
//                 <link rel="icon" href="/favicon.ico" />
//             </Head>
//             <div className="h-full w-full relative flex justify-center">
//                 <div className="w-full h-full bg-white md:rounded-tr-[100px]  max-w-7xl  py-10 relative ">
//                     <div className="absolute -top-5 -left-8  hidden md:block z-10">
//                         <img src="/assets/Soccer_ball.svg" alt="ball" className="w-24 h-24 roll" />
//                     </div>
//                     <section className="flex w-full flex-col justify-center items-center px-4 lg:px-10">
//                         <p className="text-3xl font-medium">Polo Corner</p>

//                     </section>

//                 </div>



//             </div>
//         </Layout>
//     );
// }

// export default Corner;